site_name: OnSky Smart Health Documentation
site_description: "This is the document for OnSky Smart Health Android Application"
site_author: Nguyễn Hoàng Ân

repo_name: onsky-mobileapplication/onsky-android
repo_url: http://gitlab.onskyinc.com/onsky-mobileapplication/onsky-android

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: deep orange
      accent: deep orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: deep orange
      accent: deep orange
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    - search.highlight

copyright: "&copy; 2022 Nguyễn Hoàng Ân"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anhoang241998
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html
